### ISSUE TITLE
Non-standard property forces parsing to fail

### ISSUE THREAD

**Issue by maritaria** [filecage/ical-ts#1]
I'm using the library to parse an ical string from a google calendar public url, while doing so I'm facing some challenges. I'm sure that most of the problems are because either support for the newest spec is missing or google is doing non-standard things.

A property FILENAME on an attachment `ATTACH;FILENAME="Some video.mp4";FMTTYPE=video/mp4:https://drive.google.com/file/d/.../view?usp=drive_web`

Following your source, I've fixed this by using string replacement to change FILENAME to X-FILENAME. That at least gets me further into parsing. It would be nice to have a lenient parsing option, as someone using your library I just want to have the data parsed, whether the ical is 100% standards conforming bears no meaning on my goal to derive use out of the data there-in.

Second, I also hit a problem where a `x-...` property (correctly escaped by google) appears multiple times and thus is not converted into a list property automatically. The solution here would be to allow specifying what `X-` properties are list typed, always treating `X-` props as lists, or auto-converting to a list when multiple are present.

**Comment by maritaria** [comment]
Btw, I thank you for building a modern implementation for ical parsing, I agree the others are outdated

**Comment by maritaria** [comment]
After some digging, I found the definition of the `FILENAME` property (https://www.rfc-editor.org/rfc/rfc8607.html#section-4.2)

Additionally, I discovered that "iCalendar identifier registered with IANA" as noted by [rfc5545-3.1](https://www.rfc-editor.org/rfc/rfc5545#section-3.1) are not necessarily prefixed with `IANA-`. Which is why the `FILENAME` property is failing to parse.

Following the thread of "registered with IANA" I stumbled accross the [IANA property registry](https://www.iana.org/assignments/icalendar/icalendar.xhtml) which helpfully links to all properties and their RFC.

I don't know what your vision for the library is, how much control you want to give users of the library and how much comes down to strictness. But I would suggest that where the error is thrown would be a good point to let the user decide on how to handle an unknown property, which could simply be marked as nonstandard through a boolean field.

**Comment by maritaria** [comment]
I've extracted the `VEVENT` section that has the repeating property `X-GOOGLE-CONFERENCE`. I noted that this is the only event that this had occurred on. I can only speculate as to why it would appear twice (with the same value).


<details>
<summary>Section of data</summary>



```
BEGIN:VEVENT
DTSTART:20220503T080000Z
DTEND:20220503T090000Z
DTSTAMP:20230811T122551Z
ORGANIZER;CN=redacted@example.com:mailto:redacted@example.com
UID:redacted@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=redact
 ed@example.com;X-NUM-GUESTS=0:mailto:redacted@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=redact
 ed@example.com;X-NUM-GUESTS=0:mailto:redacted@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=redact
 ed@example.com;X-NUM-GUESTS=0:mailto:redacted@example.com
X-GOOGLE-CONFERENCE:https://meet.google.com/redacted
CREATED:20220429T112003Z
DESCRIPTION:Join me for a presentation of learning and growth opportunities
  at Redacted!\n\nDeelnemen via Google Meet: https://meet.google.com/red
 acted\nOf bel: (NL) +31 redacted Pincode: redacted#\nMeer telefoonnummers:
  https://tel.meet/redacted?pin=redacted&hs=7\n\nGa voor meer informatie ov
 er Meet naar https://support.google.com/a/users/answer/9282720
LAST-MODIFIED:20220503T075313Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Growing together
TRANSP:OPAQUE
X-GOOGLE-CONFERENCE:https://meet.google.com/redacted
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
BEGIN:VALARM
ACTION:NONE
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
X-WR-ALARMUID:redacted-same-as-uid
UID:00000000-0000-0000-0000-000000000000
ACKNOWLEDGED:20220503T075313Z
X-APPLE-DEFAULT-ALARM:TRUE
END:VALARM
END:VEVENT
```

</details>


Needless to say, I redacted as much I could. I also tried to keep the alignment correct for property continuation, but I may have gotten it wrong; suffice to say that the actual problem resides in parsing the second `X-GOOGLE-CONFERENCE`.

**Comment by filecage** [comment]
Hey @maritaria, thank you for looking into this! I am currently bound to a different project and thus had not much time to put into this library, but I will return to it as soon as possible. I'm pretty sure there still is a lot of room for improvement - but it's an early release. :)

Good catch on the `IANA`-tokens not necessarily having to be prefixed, I must've overlooked that. This could be easily fixed by just not throwing anymore; there is no technical reason why anonymous properties (at least to the lib) shouldn't just be parsed apart from that I wanted to keep a stricter approach, because loosening up later is always easier than tightening.

As of the list properties I am not yet convinced what the best solution could possibly be. Treating all anonymous properties/components/parameters as list values feels like the only solution right now, but I feel like handling any listed item is a bit clunky atm and could be improved. So maybe that is a good reason to improve that.

**Comment by filecage** [comment]
@maritaria I know it's been almost a year and you've probably moved on to a different library or project. Just wanted to thank you again for your time and help, as I'm now picking up development again.

**Comment by maritaria** [comment]
You are welcome, I think it is great you took on this project because there
is not much offering for this particular format on npm.
